update (passive_anticheat): Monthly alignment
TrinityCore/TrinityCoreCustomChanges pull request #102
Opened 2023-03-30 13:15 UTC by acidmanifesto

**Changes proposed**:

- Counter Measures, which breaks select cheat apps and client's connections when in use.
- Moved exsisting presistent countermeasures to bools. (Time Manipulation)
- Added additional countermeasures (teleport\flyhack)
- Logging via conf
- Counter Measures via conf
- Counter Measures Alerts via conf
- New trinitycore_string via world sql to be applied.
- Updated Character reports with counter measure columns.
- GM .anticheat player now shows counter measure count.
- Added new method MoveFallPlayer() to assist with counter measures

New Counter Measures Deployed reporting per player's current session
![image](https://user-images.githubusercontent.com/16887899/230483338-009ffaab-f668-4350-bfb1-6f8436a211fc.png)

In game alerts for GM both screen and chat spam
![image](https://user-images.githubusercontent.com/16887899/228909452-3fc86d67-a561-4fd9-88f2-8c10f1a8a1c1.png)

Video

https://user-images.githubusercontent.com/16887899/228910878-dfd4f461-dd6d-4317-b263-0a9a45879ee4.mp4

New log examples of counter measures
```
2023-03-30_12:55:19 INFO  [anticheat] AnticheatMgr:: Speed-Hack (Speed Movement at 49 above allowed Server Set rate 7.) detected player Yarillee (GUID Full: 0x0000000000000004 Type: Player Low: 4) - Latency: 0 ms - Cheat Flagged at: .go xyz -8804.487305 686.484253 102.187088 0 3.712932
2023-03-30_12:55:19 INFO  [anticheat] AnticheatMgr:: Teleport-Hack detected player Yarillee (GUID Full: 0x0000000000000004 Type: Player Low: 4) - Latency: 0 ms - Cheat Flagged at: .go xyz -8598.000000 527.000000 109.000000 0 3.712932
2023-03-30_12:55:19 INFO  [anticheat] ANTICHEAT COUNTER MEASURE:: Yarillee TELEPORT HACK REVERTED PLAYER BACK TO .go xyz -8804.487305 686.484253 102.187050 0 3.712932
2023-03-30_12:55:30 INFO  [anticheat] AnticheatMgr:: Fly-Hack detected player Yarillee (GUID Full: 0x0000000000000004 Type: Player Low: 4) - Latency: 0 ms - Cheat Flagged at: .go xyz -8809.514648 683.804810 100.819611 0 3.606904
2023-03-30_12:55:30 INFO  [anticheat] ANTICHEAT COUNTER MEASURE:: Fly Hack detected player Yarillee (GUID Full: 0x0000000000000004 Type: Player Low: 4) - SMSG_MOVE_UNSET_CAN_FLY Set 
2023-03-30_12:55:48 INFO  [anticheat] AnticheatMgr:: Fly-Hack detected player Yarillee (GUID Full: 0x0000000000000004 Type: Player Low: 4) - Latency: 0 ms - Cheat Flagged at: .go xyz -8828.438477 690.385559 98.331505 0 2.004691
2023-03-30_12:55:48 INFO  [anticheat] ANTICHEAT COUNTER MEASURE:: Fly Hack detected player Yarillee (GUID Full: 0x0000000000000004 Type: Player Low: 4) - SMSG_MOVE_UNSET_CAN_FLY Set 
2023-03-30_12:56:54 INFO  [anticheat] AnticheatMgr:: Fly-Hack detected player Yarillee (GUID Full: 0x0000000000000004 Type: Player Low: 4) - Latency: 1 ms - Cheat Flagged at: .go xyz -8854.118164 742.426025 101.743782 0 0.241471
2023-03-30_12:56:54 INFO  [anticheat] ANTICHEAT COUNTER MEASURE:: Fly Hack detected player Yarillee (GUID Full: 0x0000000000000004 Type: Player Low: 4) - SMSG_MOVE_UNSET_CAN_FLY Set 
2023-03-30_12:57:14 INFO  [anticheat] AnticheatMgr:: Speed-Hack (Speed Movement at 20 above allowed Server Set rate 7.) detected player Yarillee (GUID Full: 0x0000000000000004 Type: Player Low: 4) - Latency: 1 ms - Cheat Flagged at: .go xyz -8849.628906 729.678650 99.732063 0 4.953861
2023-03-30_12:57:14 INFO  [anticheat] AnticheatMgr:: Teleport-Hack detected player Yarillee (GUID Full: 0x0000000000000004 Type: Player Low: 4) - Latency: 1 ms - Cheat Flagged at: .go xyz -8598.000000 527.000000 109.000000 0 4.953861
2023-03-30_12:57:14 INFO  [anticheat] ANTICHEAT COUNTER MEASURE:: Yarillee TELEPORT HACK REVERTED PLAYER BACK TO .go xyz -8849.628906 729.678650 99.732063 0 4.953861
```

FOR PEOPLE UPDATING FROM CURRENT. RUN THIS SQL ON THE CHARACTERS DB:
```
-- run only if updating from previous table versions
ALTER TABLE `daily_players_reports`
	ADD COLUMN `counter_measures_reports` BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER `op_ack_hack_reports`;
	
ALTER TABLE `players_reports_status`
	ADD COLUMN `counter_measures_reports` BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER `op_ack_hack_reports`;
```

**CONF:**
```

###################################################################################################
#   ANTICHEAT COUNTER MEASURE
#
#     Anticheat Counter Measures
#
#     Anticheat.CM.TIMEMANIPULATION
#
#       Description: Counters Time Manipulation hacks. These hacks can cause server to crash.
#
#       Default:    1 - (Enabled)
#                   0 - (Disabled)
#

Anticheat.CM.TIMEMANIPULATION = 1

#
#     Anticheat.CM.Teleport
#
#       Description: Sends player back to last gps position if player cheats and teleports.
#
#       Default:    0 - (Disabled)
#                   1 - (Enabled)
#

Anticheat.CM.Teleport = 0

#
#     Anticheat.CM.FLYHACK
#
#       Description: Sets player back to the ground if fly hack is detected
#
#       Default:    0 - (Disabled)
#                   1 - (Enabled)
#

Anticheat.CM.FLYHACK = 0
#
#     Anticheat.CM.JUMPHACK
#     Anticheat.CM.ADVJUMPHACK
#       Description: Sets player back to the ground if jump hack is detected
#
#       Default:    0 - (Disabled)
#                   1 - (Enabled)
#

Anticheat.CM.JUMPHACK = 0
Anticheat.CM.ADVJUMPHACK = 0

#
#     Anticheat.CM.IGNOREZ
#
#       Description: Sets player back to the ground if ignore-z hack is detected
#
#       Default:    0 - (Disabled)
#                   1 - (Enabled)
#

Anticheat.CM.IGNOREZ = 0

#
#     Anticheat.CM.SPEEDHACK
#
#       Description: Sets player back to allowed server rate speed when speed hack is detected
#       Default:    0 - (Disabled)
#                   1 - (Enabled)
#

Anticheat.CM.SPEEDHACK = 0

#
#     Anticheat.CM.WriteLog
#
#       Description: Enables Logging
#       Default:    0 - (Disabled)
#                   1 - (Enabled)
#

Anticheat.CM.WriteLog = 0

#
#     Anticheat.CM.ALERTSCREEN
#
#       Description: Alerts online GMs of Counter Measure being deployed via screen alert
#       Default:    0 - (Disabled)
#                   1 - (Enabled)
#

Anticheat.CM.ALERTSCREEN = 0

#
#     Anticheat.CM.ALERTCHAT
#
#       Description: Alerts online GMs of Counter Measure being deployed via chat alert
#       Default:    0 - (Disabled)
#                   1 - (Enabled)
#

Anticheat.CM.ALERTCHAT= 0
```
**Target branch(es)**: 335-passive_anticheat

**Issues addressed**: Fixes #

**Tests performed**: (Does it build, tested in-game, etc)

**Known issues and TODO list**:

- [ ] 
- [ ]

2023-03-30 13:16 UTC, acidmanifesto commented
@jackpoz review please, but do not merge.

2023-04-07 09:35 UTC, jackpoz requested changes

2023-04-07 09:35 UTC, jackpoz commented on src/server/game/Anticheat/AnticheatMgr.cpp
> +            std::string str = "|cFFFFFC00[Playername:|cFF00FFFF[|cFF60FF00" + std::string(player->GetName().c_str()) + "|cFF00FFFF] TIME MANIPULATION COUNTER MEASURE ALERT";
isn't player->GetName() already a std::string ?

2023-04-07 09:35 UTC, jackpoz commented on src/server/game/Anticheat/AnticheatMgr.cpp
> +        Player* cheatertarget = player->GetSession()->GetPlayer();
isn't player->GetSession()->GetPlayer() the same as player ?

2023-04-07 09:35 UTC, jackpoz commented on src/server/game/Movement/MotionMaster.cpp
> +// Created a new method per advise from jackpoz instead of modifying the above
Please remove my name 😄

2023-04-07 22:11 UTC, acidmanifesto commented on src/server/game/Anticheat/AnticheatMgr.cpp
> +            std::string str = "|cFFFFFC00[Playername:|cFF00FFFF[|cFF60FF00" + std::string(player->GetName().c_str()) + "|cFF00FFFF] TIME MANIPULATION COUNTER MEASURE ALERT";
updated

2023-04-07 22:26 UTC, acidmanifesto commented on src/server/game/Anticheat/AnticheatMgr.cpp
> +        Player* cheatertarget = player->GetSession()->GetPlayer();
correct it is.
Corected

2023-04-11 21:00 UTC, jackpoz requested changes

2023-04-11 21:00 UTC, jackpoz commented on src/server/game/World/World.cpp
> +    m_bool_configs[CONFIG_ANTICHEAT_CM_TIMEMANIPULATION] = sConfigMgr->GetBoolDefault("Anticheat.CM.TIMEMANIPULATION", false);
usually the default values here should match the default values in worldserver.conf.dist , but I see that Anticheat.CM.TIMEMANIPULATION is enabled by default. Should it be enabled or disabled ?

2023-04-11 21:00 UTC, jackpoz commented on src/server/game/Anticheat/AnticheatMgr.cpp
> +            std::string str = "|cFFFFFC00[Playername:|cFF00FFFF[|cFF60FF00" + std::string(player->GetName()) + "|cFF00FFFF] Auto Kicked for Reaching Cheat Threshhold!";
```suggestion
            std::string str = "|cFFFFFC00[Playername:|cFF00FFFF[|cFF60FF00" + player->GetName() + "|cFF00FFFF] Auto Kicked for Reaching Cheat Threshhold!";
```

2023-04-11 21:00 UTC, jackpoz commented on src/server/game/Anticheat/AnticheatMgr.cpp
> +            std::string str = "|cFFFFFC00[Playername:|cFF00FFFF[|cFF60FF00" + std::string(player->GetName()) + "|cFF00FFFF] Auto Kicked for Reaching Cheat Threshhold!";
Pretty much wherever you used `std::string(player->GetName())` or `std::string(player->GetName().c_str())` you should just use `player->GetName()`.

player->GetName() returns a string already so there's no need to call std::string( ) . Did this code get accepted flawlessly to another certain project ?

2023-04-12 18:31 UTC, acidmanifesto commented on src/server/game/World/World.cpp
> +    m_bool_configs[CONFIG_ANTICHEAT_CM_TIMEMANIPULATION] = sConfigMgr->GetBoolDefault("Anticheat.CM.TIMEMANIPULATION", false);
Hmm... well i was not certain if it was recommended to leave it iff by default in the core. However i do feel strongly recommend it is on by default. Should i change that in the conf or should i change up the core to have it as on?

2023-04-12 18:32 UTC, acidmanifesto commented on src/server/game/Anticheat/AnticheatMgr.cpp
> +            std::string str = "|cFFFFFC00[Playername:|cFF00FFFF[|cFF60FF00" + std::string(player->GetName()) + "|cFF00FFFF] Auto Kicked for Reaching Cheat Threshhold!";
The workflow is set up differently, so many things thats usually accepted there shows up as errors here. But i have no issues making the changes in a bit.

2023-04-16 11:02 UTC, jackpoz commented on src/server/game/World/World.cpp
> +    m_bool_configs[CONFIG_ANTICHEAT_CM_TIMEMANIPULATION] = sConfigMgr->GetBoolDefault("Anticheat.CM.TIMEMANIPULATION", false);
that's up to you, you can think about it more, I just want both the same setting in .conf and .cpp

2023-04-16 17:36 UTC, acidmanifesto commented on src/server/game/World/World.cpp
> +    m_bool_configs[CONFIG_ANTICHEAT_CM_TIMEMANIPULATION] = sConfigMgr->GetBoolDefault("Anticheat.CM.TIMEMANIPULATION", false);
i went ahead and adjusted it to true

2023-05-06 11:49 UTC, jackpoz approved these changes

2023-05-06 17:16 UTC, merged